background=0xBF111214
base=0xD9111214
text=0xFFE8E8EB
alternate_base=0xFF18191C
bright_text=0xFFFFFFFF
accent=0xFFE8E8EB
accent_secondary=0xFFB5B5B8
font_family=Geist
font_family_monospace=Geist Mono

h1_size=20
h2_size=16
h3_size=14
font_size=13
small_font_size=11
icon_theme=
rounding_large=2
rounding_small=0
